[package]
name = "spl-governance-cli"
version = "0.0.1"
description = "Solana Program Library Governance Tools"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
clap = "2.33.3"
solana-clap-utils = "2.1.0"
solana-cli-config = "2.1.0"
solana-client = "2.1.0"
solana-logger = "2.1.0"
solana-sdk = "2.1.0"
spl-governance = { path = "../program", features = ["no-entrypoint" ]}

[[bin]]
name = "spl-governance"
path = "src/main.rs"

