[package]
name = "spl-zol"
version = "0.1.0"
description = "Solana Program Library ZOL"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
default = ["elgamal_ristretto/program"]

[dependencies]
bincode = "1.3"
borsh = "0.8"
bulletproofs = { version = "4", git = "https://github.com/garious/bulletproofs", rev = "200bbcd4cb9ad6fc533232fcd4a00c893921f184" }
curve25519-dalek = { package = "curve25519-dalek-ng", default-features = false, git = "https://github.com/garious/curve25519-dalek", rev = "fcef1fa11b3d3e89a1abf8986386ba9ae375392c", features = ["borsh"] }
elgamal_ristretto = { git = "https://github.com/garious/elgamal", rev = "892dbe115104bcb8cc26d79f9676c836ff6c018e", default-features = false }
getrandom = { version = "0.1.15", features = ["dummy"] }
merlin = "3"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8"
solana-program = "1.5.6"
thiserror = "1.0"

[dev-dependencies]
rand_core = "0.6"
solana-sdk = "1.5.6"

[lib]
crate-type = ["cdylib", "lib"]
