# Validate your changes with:
#
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/
#
# https://doc.mergify.io/
pull_request_rules:
  - name: automatic merge (squash) on CI success
    conditions:
      - check-success=Travis CI - Pull Request
      - check-success=rustfmt
      - check-success=clippy
      - check-success=list_bpf_programs
      - check-success=cargo_test
      - check-success=js_token
      - check-success=js_token_swap
      - check-success=js_token_lending
      - check-success=Test themis/client_ristretto
      - check-success=Build Program memo/program
      - check-success=Build Program shared-memory/program
      - check-success=Build Program stake-pool/program
      - check-success=Build Program themis/program_ristretto
      - check-success=Build Program token-lending/program
      - check-success=Build Program token-swap/program
      - check-success=Build Program token/program-v3
      - check-success=Build Program token/program
      - label=automerge
      - author≠@dont-squash-my-commits
    actions:
      merge:
        method: squash
  # Join the dont-squash-my-commits group if you won't like your commits squashed
  - name: automatic merge (rebase) on CI success
    conditions:
      - check-success=Travis CI - Pull Request
      - check-success=rustfmt
      - check-success=clippy
      - check-success=list_bpf_programs
      - check-success=cargo_test
      - check-success=js_token
      - check-success=js_token_swap
      - check-success=js_token_lending
      - check-success=Test themis/client_ristretto
      - check-success=Build Program memo/program
      - check-success=Build Program shared-memory/program
      - check-success=Build Program stake-pool/program
      - check-success=Build Program themis/program_ristretto
      - check-success=Build Program token-lending/program
      - check-success=Build Program token-swap/program
      - check-success=Build Program token/program-v3
      - check-success=Build Program token/program
      - label=automerge
      - author=@dont-squash-my-commits
    actions:
      merge:
        method: rebase
  - name: remove automerge label on CI failure
    conditions:
      - label=automerge
      - "#status-failure!=0"
    actions:
      label:
        remove:
          - automerge
      comment:
        message: automerge label removed due to a CI failure
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
        changes_requested: true
