
[package]
name = "spl-themis-client"
version = "0.1.0"
description = "SPL THEMIS client"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program"]
default = ["solana-sdk/default"]

[dependencies]

[dev-dependencies]
curve25519-dalek = { version = "2.0.0", default-features = false, features = ["serde"] }
elgamal_ristretto = { git = "https://github.com/iquerejeta/elgamal", rev = "05e5481e5b7c5b596963ebe0465aab7879cd0b8b" }
solana-banks-client = "1.3.12"
solana-banks-server = "1.3.12"
solana-runtime = "1.3.12"
solana-sdk = "1.3.12"
spl-themis = { version = "0.1.0", path = "../program" }
tokio = "0.2"

[lib]
crate-type = ["cdylib", "lib"]
