[package]
name = "spl-token-group-example"
version = "0.1.0"
description = "Solana Program Library Token Group Example Program"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
borsh = "0.10"
solana-program = "1.16.3"
spl-discriminator = { version = "0.1.0" , path = "../../libraries/discriminator" }
spl-pod = { version = "0.1.0" , path = "../../libraries/pod" }
spl-token-2022 = { version = "0.7.0", path = "../../token/program-2022" }
spl-token-group-interface = { version = "0.1.0", path = "../interface" }
spl-token-metadata-interface = { version = "0.1.0", path = "../../token-metadata/interface" }
spl-tlv-account-resolution = { version = "0.2.0" , path = "../../libraries/tlv-account-resolution" }
spl-type-length-value = { version = "0.2.0" , path = "../../libraries/type-length-value" }

[dev-dependencies]
solana-program-test = "1.16.3"
solana-sdk = "1.16.3"
spl-token-client = { version = "0.5", path = "../../token/client" }
test-case = "3.1"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]