[package]
name = "spl-single-validator-manager"
version = "0.1.0"
description = "Solana Program Library Single Validator Stake Pool Manager"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
borsh = "0.9"
bytemuck = "1.8"
mpl-token-metadata =  { version = "1.3.1", features = [ "no-entrypoint" ] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.4"
serde = "1.0.130"
serde_derive = "1.0.103"
solana-program = "1.14.10"
spl-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-stake-pool = { version = "0.7", path = "../../stake-pool/program", features = [ "no-entrypoint" ] }
spl-token = { version = "3.5", path = "../../token/program", features = [ "no-entrypoint" ] }
spl-token-2022 = { version = "0.5", path = "../../token/program-2022", features = [ "no-entrypoint" ] }
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "1.14.10"
solana-sdk = "1.14.10"
solana-vote-program = "1.14.10"
spl-token = { version = "3.5", path = "../../token/program", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib", "lib"]
