comment_width = 80
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
group_imports = "One"
ignore = [
  "**/*/entrypoint.rs"
]
imports_granularity = "One"
wrap_comments = true
