[package]
name = "permissioned-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]
name = "permissioned_token"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test = []

[dependencies]
solana-program = "1.10.32"
shank = "^0.0.5"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.1.1", features = [ "no-entrypoint", ] }
thiserror = "^1.0.24"
borsh = "0.9.3"

[dev-dependencies]
solana-program-test = "1.10.32"
solana-sdk = "1.10.32"
tokio = { version = "1.8.4", features = ["full"] }
lightweight-solana-client = "0.1.2"

[profile.release]
lto = "fat"
codegen-units = 1
overflow-checks = true
