[package]
name = "spl-discriminator"
version = "0.1.0"
description = "Solana Program Library 8-Byte Discriminator Management"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
solana-program = "1.14.12"
spl-discriminator-derive = { version = "0.1.0", path = "./derive" }
spl-discriminator-syn = { version = "0.1.0", path = "./syn" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
