[package]
name = "spl-serde"
version = "0.1.0"
description = "" # todo add
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
spl-serde-derive = { version = "0.1.0", path = "./derive" }
serde = "1.0.188"
serde_with = "3.3.0"

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
