[package]
name = "spl-type-length-value-derive"
version = "0.1.0"
description = "Derive macro library for the `spl-type-length-value` library"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
spl-type-length-value-syn = { version = "0.1.0", path = "../syn" }
syn = { version = "2.0", features = ["extra-traits"] }